import type { Metadata } from 'next';
import { Navbar } from '@/components/navbar';
import '../globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col items-center min-h-screen bg-background font-sans antialiased">
      <Navbar />
      {children}
    </div>
  );
}
